---
# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Setup/install tasks.
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Template exports file.
  template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: 0644
  notify: restart nfs-server

- name: Ensure nfs is running.
  service: 
      name: "{{ nfs_server_daemon }}"
      state: "{{ nfs_server_state }}"
      enabled: "{{ nfs_server_enabled }}"
  when: nfs_exports|length and nfs_service_managed

- name: Template empty /etc/sysconfig/nfs in EL7 to prevent duplicate configuration.
  template:
    src: sysconfig-nfs.j2
    dest: /etc/sysconfig/nfs
    owner: root
    group: root
    mode: 0644
    backup: true
  when: nfs_exports|length and nfs_service_managed and ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"
  notify:
    - restart nfs-config on EL7
    - restart nfs-server

- name: Template /etc/nfs.conf.
  template:
    src: nfs.conf.j2
    dest: /etc/nfs.conf
    owner: root
    group: root
    mode: 0644
  when: nfs_exports|length and nfs_service_managed and ansible_os_family == "RedHat"
  notify:
    - restart nfs-server
